version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: go_rate_limiter
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis